### ISSUE TITLE
Overlapping and oversized number label on the scale

### ISSUE THREAD

**Issue by haoxue-fan** [gouverneurp/eVAS#2]
I tried to add more options for the scale and noticed that although I can control the size of the text labels, I cannot control the size for the numerical labels. Additionally, when the interval has multiple decimals (e.g., 1/7) the numerical labels will overlap with each other (see the screenshot below).

<img width="1677" alt="Screenshot 2024-06-26 at 2 06 14 PM" src="https://github.com/gouverneurp/eVAS/assets/42018862/6e91fcb3-e3e7-4caf-add3-2610eb8fc564">

**Comment by gouverneurp** [comment]
Thank you again for your comments!
Now you can change the font size of the numbers ([commit](https://github.com/gouverneurp/eVAS/commit/552baeead4687fe672a7415f3f7aa6ac4a27cb8e)) and the values are rounded to 2 digits ([commit](https://github.com/gouverneurp/eVAS/commit/937447ec2e42bef8ddcb93535f061094be5d5485)). While I hope this fixes the problem, I think the user will always be able to visually "break" the scale with strange configurations as we have a very dynamic and changeable setup. 

Hopefully, this will increase the possibilities for desired and valid scales!
