### ISSUE TITLE
Conflict between installing eVAS via python and standalone (Mac)

### ISSUE THREAD

**Issue by haoxue-fan** [gouverneurp/eVAS#3]
I first installed eVAS through the standalone app for Mac, which worked great. I then tried to install it through the pip install method, and when I ran `python eVAS.py`, I saw the message 'You need to add eVAS to the Accessibility and Input Monitoring apps and restart it. Open the system preferences?' even though I have already added the eVAS standalone to the allowed list. I wonder whether there is anyway to prevent this warning, or maybe just make it clearer in the README that people should only use one of the way to install eVAS?

**Comment by gouverneurp** [comment]
To be honest, I cannot really reproduce this problem. Is it related to the fact that you also need to add Python to the Accessibility and Input Monitoring applications?
What would you recommend I do?

**Comment by haoxue-fan** [comment]
I am not sure what the root issue is, but on a second thought I guess it may not be too common for people to both install it as standalone and through command line (or if they do that, they may be able to figure out how to make it work by probably de-installing the standalone version). I think this was just a minor point (and I happen to encounter this during testing), so I would recommend just to close this issue for now!
