### ISSUE TITLE
The relationship between Install instructions section 'How to use' and 'Build executables'

### ISSUE THREAD

**Issue by haoxue-fan** [gouverneurp/eVAS#4]
I was a little confused when I go over the instructions for sections 'How to use' and 'Build executables'. Is the latter necessary if I want to open it through the command line? Would be great if you can add some lines explaining the relationship between these two parts, or more specifically, when will a person follows the instructions under the section 'Build executables'.

**Comment by gouverneurp** [comment]
No, the last part is not needed to run eVAS from the command line. If you have set up everything related to the Python section, then __python eVAS.py__ is sufficient to run eVAS from the command line.

Building executables can be useful when researchers have modified the code for whatever reason (maybe their own specific project?) and want to create standalone executables as they can be easier to use.

I have updated the README file slightly to have more information on this ([commit](https://github.com/gouverneurp/eVAS/commit/9c44df08d99388b98586b18598cb4f51eafb7f62)).
Should I add more information?

**Comment by haoxue-fan** [comment]
looks good to me! thanks
