### ISSUE TITLE
Save metadata (ini setup) with each csv file

### ISSUE THREAD

**Issue by haoxue-fan** [gouverneurp/eVAS#5]
(This is more of an extra feature request, so feel free to say no/put it on the back burner!)

Basically I was wondering whether the current software can save the current config.ini setup together with the csv of the eVAS data. The motivation being that the researcher may use the same rating scale with different prompts or general setup when tackling different research questions, and it would be helpful to have a 'screenshot' of what the eVAS was used to measure.

**Comment by gouverneurp** [comment]
As I said, I like your ideas for improving eVAS. 
Please have a look at the following [commit](https://github.com/gouverneurp/eVAS/commit/5900889d064f60cf46288daecc3a0b36757d7e5b), which introduces a parameter that can be set to save the config at the top of the CSV file.
Is this what you had in mind?
As this is a major change (and not really the way CSV files look), I have set the default of the option to False. Is this OK with you? Do you have any other ideas for improving this feature?

**Comment by haoxue-fan** [comment]
that looks good to me and I think is perfect! thanks! :)
