### ISSUE TITLE
Unexpected exiting when pressing 'caps lock' on Mac standalone app

### ISSUE THREAD

**Issue by haoxue-fan** [gouverneurp/eVAS#6]
The Mac standalone app exits after I press caps lock. There will be one data file saved, but no data inside (i.e., the size for the file is 0 byte)

I am using Mac Sonoma 14.2.1 and python 3.11.4.

**Comment by gouverneurp** [comment]
I can actually reproduce this bug. I think it is closely related to problems between Tkinter and pynput (bibliography to detect keystrokes). I have not found much online to solve the problems. I will commit a change that will reduce possible crashes, but not fix them completely in the near future.

**Comment by gouverneurp** [comment]
As mentioned, I have been working on a fix for the last days.
Here is the possible solution:
https://github.com/gouverneurp/eVAS/commit/477d30c255570a640163faef09c941c755c02104

Can you check it again?
I will also release a built version later on.

**Comment by haoxue-fan** [comment]
looks good to me, thanks!
