### ISSUE TITLE
eVAS cannot run when setting trigger_thermode = True

### ISSUE THREAD

**Issue by haoxue-fan** [gouverneurp/eVAS#7]
^ the issue was described in the title. 

I assume that the trigger_thermode was a feature that the researcher has used in specific projects. As an app facing general audience, I am wondering whether it may be easier just to take out of this input field, or add more comments in ini briefly describing what it is used for and suggest people to keep it as False unless they are doing related research?

**Comment by gouverneurp** [comment]
In fact, this is a very specific feature created for a particular use case in a project. When the eVAS starts to record data, a trigger signal is sent to a 'QST.LAB TCS2' thermode device. 

I have fixed the problem of it crashing on Mac and Linux ([commit](https://github.com/gouverneurp/eVAS/commit/49d398c4968a9a706ec8bd986b7d179b83284b3f)) and added more detailed information about it in the config file, in particular that it only works on Windows.

Let me know if it is better to remove it!

**Comment by haoxue-fan** [comment]
looks good to me, thanks!
